#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub(crate) enum RegistryId<'a> {
    Bool,
    UInt8,
    UInt16,
    UInt32,
    UInt64,
    UInt128,
    Int8,
    Int16,
    Int32,
    Int64,
    Int128,
    URange8,
    URange16,
    URange32,
    URange64,
    URange128,
    Range8,
    Range16,
    Range32,
    Range64,
    Range128,
    Float32,
    Float64,
    Str,
    Ptr,
    Ref,
    Tuple,
    Array,
    Func,
    Node,
    Custom(&'a str),
}

impl<'a> RegistryId<'a> {
    pub(crate) fn to_str(&self) -> &'a str {
        match self {
            RegistryId::Bool => "Bool",
            RegistryId::UInt8 => "UInt8",
            RegistryId::UInt16 => "UInt16",
            RegistryId::UInt32 => "UInt32",
            RegistryId::UInt64 => "UInt64",
            RegistryId::UInt128 => "UInt128",
            RegistryId::Int8 => "Int8",
            RegistryId::Int16 => "Int16",
            RegistryId::Int32 => "Int32",
            RegistryId::Int64 => "Int64",
            RegistryId::Int128 => "Int128",
            RegistryId::URange8 => "URange8",
            RegistryId::URange16 => "URange16",
            RegistryId::URange32 => "URange32",
            RegistryId::URange64 => "URange64",
            RegistryId::URange128 => "URange128",
            RegistryId::Range8 => "Range8",
            RegistryId::Range16 => "Range16",
            RegistryId::Range32 => "Range32",
            RegistryId::Range64 => "Range64",
            RegistryId::Range128 => "Range128",
            RegistryId::Float32 => "Float32",
            RegistryId::Float64 => "Float64",
            RegistryId::Str => "Str",
            RegistryId::Ptr => "Ptr",
            RegistryId::Ref => "Ref",
            RegistryId::Tuple => "Tuple",
            RegistryId::Array => "Array",
            RegistryId::Func => "Func",
            RegistryId::Node => "Node",
            RegistryId::Custom(id) => *id,
        }
    }

    pub(crate) fn from_str(s: &'a str) -> Self {
        match s {
            "Bool" => RegistryId::Bool,
            "UInt8" => RegistryId::UInt8,
            "UInt16" => RegistryId::UInt16,
            "UInt32" => RegistryId::UInt32,
            "UInt64" => RegistryId::UInt64,
            "UInt128" => RegistryId::UInt128,
            "Int8" => RegistryId::Int8,
            "Int16" => RegistryId::Int16,
            "Int32" => RegistryId::Int32,
            "Int64" => RegistryId::Int64,
            "Int128" => RegistryId::Int128,
            "URange8" => RegistryId::URange8,
            "URange16" => RegistryId::URange16,
            "URange32" => RegistryId::URange32,
            "URange64" => RegistryId::URange64,
            "URange128" => RegistryId::URange128,
            "Range8" => RegistryId::Range8,
            "Range16" => RegistryId::Range16,
            "Range32" => RegistryId::Range32,
            "Range64" => RegistryId::Range64,
            "Range128" => RegistryId::Range128,
            "Float32" => RegistryId::Float32,
            "Float64" => RegistryId::Float64,
            "Str" => RegistryId::Str,
            "Ptr" => RegistryId::Ptr,
            "Ref" => RegistryId::Ref,
            "Tuple" => RegistryId::Tuple,
            "Array" => RegistryId::Array,
            "Func" => RegistryId::Func,
            "Node" => RegistryId::Node,
            id => RegistryId::Custom(id),
        }
    }
}
